cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

timeless_men/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('about/', include('about.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


WARRANTY_CHOICES = [('1', 'none'), ('2', '2 years'), ('3', '3 years'),
                    ('5', '5 years'), ('l', 'life')]


class Product(models.Model):
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    case = models.CharField(max_length=254, null=True, blank=True)
    strap = models.CharField(max_length=254, null=True, blank=True)
    brand = models.CharField(max_length=254, null=True, blank=True)
    year_warranty = models.CharField(max_length=1,
                                     choices=WARRANTY_CHOICES, default='1')
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

cart/views.py
from django.shortcuts import (
    render, redirect, reverse, get_object_or_404, HttpResponse
)
from django.contrib import messages
from products.models import Product

# Create your views here.


def view_cart(request):
    """ A view that renders the cart contents page """

    return render(request, 'cart/cart.html')


def add_to_cart(request, item_id):
    """ Add a quantity of the specified product to the shopping cart """

    product = get_object_or_404(Product, pk=item_id)
    quantity = int(request.POST.get('quantity'))
    redirect_url = request.POST.get('redirect_url')
    warranty = None
    if 'product_warranty' in request.POST:
        warranty = request.POST['product_warranty']
    cart = request.session.get('cart', {})

    if warranty:
        if item_id in list(cart.keys()):
            if warranty in cart[item_id]['items_by_warranty'].keys():
                cart[item_id]['items_by_warranty'][warranty] += quantity
                messages.success(
                    request, f'Updated warranty {warranty.upper()} {product.name} quantity to {cart[item_id]["items_by_warranty"][warranty]}')
            else:
                cart[item_id]['items_by_warranty'][warranty] = quantity
                messages.success(
                    request, f'Added warranty {warranty.upper()} {product.name} to your cart.')
        else:
            cart[item_id] = {'items_by_warranty': {warranty: quantity}}
            messages.success(
                request, f'Added warranty {warranty.upper()} {product.name} to your cart.')
    else:
        if item_id in list(cart.keys()):
            cart[item_id] += quantity
            messages.success(
                request, f'Updated {product.name} quantity to {cart[item_id]}')
        else:
            cart[item_id] = quantity
            messages.success(request, f'Added {product.name} to your cart')

    request.session['cart'] = cart
    return redirect(redirect_url)


def adjust_cart(request, item_id):
    """Adjust the quantity of the specified product to the specified amount"""

    product = get_object_or_404(Product, pk=item_id)
    quantity = int(request.POST.get('quantity'))
    warranty = None
    if 'product_warranty' in request.POST:
        warranty = request.POST['product_warranty']
    cart = request.session.get('cart', {})

    if warranty:
        if quantity > 0:
            cart[item_id]['items_by_warranty'][warranty] = quantity
            messages.success(
                    request, f'Updated warranty {warranty.upper()} {product.name} quantity to {cart[item_id]["items_by_warranty"][warranty]}')
        else:
            del cart[item_id]['items_by_warranty'][warranty]
            if not cart[item_id]['items_by_warranty']:
                cart.pop(item_id)
            messages.success(request, f'Removed warranty {warranty.upper()} {product.name} from your cart')
    else:
        if quantity > 0:
            cart[item_id] = quantity
            messages.success(request, f'Updated {product.name} quantity to {cart[item_id]}')
        else:
            cart.pop(item_id)
            messages.success(request, f'Removed {product.name} from your cart')

    request.session['cart'] = cart
    return redirect(reverse('view_cart'))


def remove_from_cart(request, item_id):
    """Remove the item from the shopping cart"""

    try:
        product = get_object_or_404(Product, pk=item_id)
        warranty = None
        if 'product_warranty' in request.POST:
            warranty = request.POST['product_warranty']
        cart = request.session.get('cart', {})

        if warranty:
            del cart[item_id]['items_by_warranty'][warranty]
            if not cart[item_id]['items_by_warranty']:
                cart.pop(item_id)
            messages.success(request, f'Removed warranty {warranty.upper()} {product.name} from your cart')
        else:
            cart.pop(item_id)
            messages.success(request, f'Removed {product.name} from your cart')

        request.session['cart'] = cart
        return HttpResponse(status=200)

    except Exception as e:
        messages.error(request, f'Error removing item: {e}')
        return HttpResponse(status=500)

cart/templates/cart/cart-total.html
<h6><strong>Cart Total: €{{ total|floatformat:2 }}</strong></h6>
<h6>Delivery: €{{ delivery|floatformat:2 }}</h6>
<h5 class="mt-4"><strong>Grand Total: €{{ grand_total|floatformat:2 }}</strong></h5>
{% if free_delivery_delta > 0 %}
    <p class="mb-1 text-danger">
        You could get free delivery by spending just <strong>€{{ free_delivery_delta }}</strong> more!
    </p>
{% endif %}

cart/templates/cart/cart.html
{% extends "base.html" %}
{% load static %}
{% load cart_tools %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container pb-3 mb-3">
        <div class="row">
            <div class="col">
                <h2 class="logo-font my-4">Shopping Cart</h2>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col" id="cart-table">
                {% if cart_items %}
                <!-- display for mobile -->
                    <div class="d-block d-md-none">
                        <div class="row">
                            <div class="col">
                                {% include "cart/cart-total.html" %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                {% include "cart/checkout-buttons.html" %}
                                <p class="text-muted mb-5">A summary of your cart contents is below</p>
                            </div>
                        </div>
                        {% for item in cart_items %}
                            <div class="row">
                                <div class="col-12 col-sm-6 mb-2">
                                    {% include "cart/product-image.html" %}
                                </div>
                                <div class="col-12 col-sm-6 mb-2">
                                    {% include "cart/product-info.html" %}
                                </div>
                                <div class="col-12 col-sm-6 order-sm-last">
                                    <p class="my-0">Price Each: €{{ item.product.price }}</p>
                                    <p><strong>Subtotal: </strong>€{{ item.product.price | calc_subtotal:item.quantity }}</p>
                                </div>
                                <div class="col-12 col-sm-6">
                                    {% include "cart/quantity-form.html" %}
                                </div>
                            </div>
                            <div class="row"><div class="col"><hr></div></div>
                        {% endfor %}
                        <div class="btt-button shadow-sm rounded-0 border border-black">
                            <a class="btt-link d-flex h-100">
                                <i class="fas fa-arrow-up text-black mx-auto my-auto"></i>
                            </a>	
                        </div>
                    </div>
                    <!-- display for larger screens -->
                    <div class="table-responsive rounded d-none d-md-block">
                        <table class="table table-sm table-borderless">
                            <thead class="text-black">
                                <tr>
                                    <th scope="col">Product Info</th>
                                    <th scope="col"></th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Qty</th>
                                    <th scope="col">Subtotal</th>
                                </tr>
                            </thead>
                            {% for item in cart_items %}
                                <tr>
                                    <td class="p-3 w-25" id="product-image">
                                        {% include "cart/product-image.html" %}
                                    </td>
                                    <td class="py-3" id="product-info">
                                        {% include "cart/product-info.html" %}
                                    </td>
                                    <td class="py-3" id="product-price">
                                        <p class="my-0">€{{ item.product.price }}</p>
                                    </td>
                                    <td class="py-3 w-25" id="quantity-form">
                                        {% include "cart/quantity-form.html" %}
                                    </td>
                                    <td class="py-3" id="cart-subtotal">
                                        <p class="my-0">€{{ item.product.price | calc_subtotal:item.quantity }}</p>
                                    </td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td colspan="5" class="pt-5 text-right" id="cart-total">
                                    {% include "cart/cart-total.html" %}
                                </td>
                            </tr>
                            <tr>
                                <td colspan="5" class="text-right" id="checkout-buttons">
                                    {% include "cart/checkout-buttons.html" %}
                                </td>
                            </tr>
                        </table>
                    </div>
                {% else %}
                    <p class="lead my-5">Your cart is empty.</p>
                    <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 btn-lg">
                        <span class="icon">
                            <i class="fas fa-chevron-left"></i>
                        </span>
                        <span class="text-uppercase">Keep Shopping</span>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock %}

{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $('.btt-link').click(function(e) {
        window.scrollTo(0,0)
    })
</script>
{% include 'products/includes/quantity_input_script.html' %}

<script type="text/javascript">
    // Update quantity on click
    $('.update-link').click(function(e) {
        var form = $(this).prev('.update-form');
        form.submit();
    })

    // Remove item and reload on click
    $('.remove-item').click(function(e) {
        var csrfToken = "{{ csrf_token }}";
        var itemId = $(this).attr('id').split('remove_')[1];
        var warranty = $(this).data('product_warranty');
        var url = `/cart/remove/${itemId}/`;
        var data = {'csrfmiddlewaretoken': csrfToken, 'product_warranty': warranty};

        $.post(url, data)
        .done(function() {
            location.reload();
        });
    })
</script>
    {% endblock %}

cart/templates/cart/checkout-buttons.html
<a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 btn-lg">
    <span class="icon">
        <i class="fas fa-chevron-left"></i>
    </span>
    <span class="text-uppercase" id="cart-logical-keep">Keep Shopping</span>
</a>
<a href="{% url 'checkout' %}" class="btn btn-dark rounded-0 btn-lg">
    <span class="text-uppercase" id="cart-logical-secure">Secure Checkout</span>
    <span class="icon">
        <i class="fas fa-lock"></i>
    </span>
</a>

cart/templates/cart/product-image.html
{% if item.product.image %}
<img class="img-fluid rounded" src="{{ item.product.image.url }}"
    alt="{{ item.product.name }}">
{% else %}
<img class="img-fluid rounded" src="{{ MEDIA_URL }}noimage.png"
    alt="{{ item.product.name }}">
{% endif %}

cart/templates/cart/product-info.html
<p class="my-0"><strong>{{ item.product.name }}</strong></p>
<p class="my-0"><strong>{{ item.product.brand }}</strong></p>
<p class="my-0"><strong>Warranty:</strong>
    {{ item.product.get_year_warranty_display|title }}
</p>
<p class="my-0 small text-muted">SKU: {{ item.product.sku|upper }}</p>

cart/templates/cart/quantity-form.html
<form class="form update-form" method="POST" action="{% url 'adjust_cart' item.item_id %}">
    {% csrf_token %}
    <div class="form-group">
        <div class="input-group">
            <div class="input-group-prepend">
                <button class="decrement-qty btn btn-sm rounded-0" 
                    data-item_id="{{ item.item_id }}" id="decrement-qty_{{ item.item_id }}">
                    <span>
                        <i class="fas fa-minus fa-sm"></i>
                    </span>
                </button>
            </div>
            <input class="form-control form-control-sm qty_input" type="number"
                name="quantity" value="{{ item.quantity }}" min="1" max="99"
                data-item_id="{{ item.item_id }}"
                id="id_qty_{{ item.item_id }}">
            <div class="input-group-append">
                <button class="increment-qty btn btn-sm rounded-0"
                    data-item_id="{{ item.item_id }}" id="increment-qty_{{ item.item_id }}">
                    <span>
                        <i class="fas fa-plus fa-sm"></i>
                    </span>
                </button>
            </div>
            {% if item.product.year_warranty %}
                <input type="hidden" name="product_warranty" value="{{ item.warranty }}">
            {% endif %}
        </div>
    </div>
</form>
<a class="update-link text-info"><small>Update</small></a>
<a class="remove-item text-danger float-right" id="remove_{{ item.item_id }}" 
data-product_warranty="{{ item.warranty }}"><small>Remove</small></a>